### ISSUE TITLE
Error playing MPD

### ISSUE THREAD

**Issue by Waldmann94** [ldecicco/tapas#10]
I am trying to use my own mpd with your TAPAS Player. When using your suggested MPD things work fine, but I receive the following Errors:
2016-12-15 13:50:50+0100 [-] Log opened.
2016-12-15 13:50:50+0100 [-] trying to open fifo
2016-12-15 13:50:50+0100 [-] URLtoMyMPD.mpd
2016-12-15 13:50:50+0100 [-] Traceback (most recent call last):
2016-12-15 13:50:50+0100 [-]   File "TAPAS/play.py", line 139, in <module>
2016-12-15 13:50:50+0100 [-]     select_player()
2016-12-15 13:50:50+0100 [-]   File "TAPAS/play.py", line 131, in select_player
2016-12-15 13:50:50+0100 [-]     player.play()
2016-12-15 13:50:50+0100 [-]   File "TAPAS/TapasPlayer.py", line 123, in play
2016-12-15 13:50:50+0100 [-]     self.parser.loadPlaylist()
2016-12-15 13:50:50+0100 [-]   File "TAPAS/parsers/DASH_mp4Parser.py", line 104, in loadPlaylist
2016-12-15 13:50:50+0100 [-]     if "@range" in json_representation[j]["SegmentBase"]["Initialization"].keys():
2016-12-15 13:50:50+0100 [-] KeyError: 'SegmentBase'

Looking at both MPD files I see the following for any one representation:

```
<SegmentTemplate duration="2000" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/$Number$.m4s" startNumber="1" timescale="1000"/>
<Representation bandwidth="1018420" codecs="avc1.4D401F" frameRate="24" height="480" id="V4" scanType="progressive" mimeType="video/mp4" width="1128"/>
```

```
<Representation bandwidth="869460" codecs="avc1.4d401e" height="480" id="3" mimeType="video/mp4" width="854">
        <BaseURL>car-20120827-87.mp4</BaseURL>
        <SegmentBase indexRange="708-1183">
          <Initialization range="0-707" />
        </SegmentBase>
      </Representation>
```

Does your player only accept this one certain form of encoding? 

Best regards
Silvio Waldmann

**Comment by pckbls** [comment]
Hi there,

Indeed I've encountered the same problems when working with TAPAS. In fact it does not accept all variants of MPEG DASH manifest files. I've created my test sequences with `mp4box` and the following parameters:
```
mp4box -dash 2000 -profile ondemand -single-segment your_input_file.mp4
```
TAPAS should be able to work with those.
